spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/post;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: false
  h2:
    console:
      enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true